#!/bin/bash
#PBS -l select=1:ncpus=4:mem=48gb:ngpus=1:gpu_type=L40S
#PBS -l walltime=72:00:00

eval "$(~/anaconda3/bin/conda shell.bash hook)"

source activate research_env

#conda install python=3.10.12

#python3 -m pip install -r /rds/general/user/zr523/home/researchProject/forecast-diffmodels/imagen/requirements.txt

cd /rds/general/user/zr523/home/researchProject/

cd imagen-pytorch
python setup.py develop
cd ..

cd forecast-diffmodels/imagen/64_FC

#accelerate config

python v_64_FC.py -mode execute -epochs 600